services:

  myteamshub.identityserver.api:
    container_name: myteamshub.identityserver.api
    image: ${DOCKER_REGISTRY-}myteamshubidentityserverapi
    build:
      context: .
      dockerfile: src/MyTeamsHub.IdentityServer.API/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
