apiVersion: v1
kind: Service
metadata:
  name: my-teams-hub-api-service
spec:
  selector:
    app: my-teams-hub-api  # Make sure this matches the label in your Deployment
  ports:
    - protocol: TCP
      port: 80  # The port the service will expose inside the cluster
      targetPort: 4000  # The port your container is running on
  type: LoadBalancer  # If you want to expose it to the outside world
